import './red-black-tree.mjs'
import './y-array.tests.mjs'
import './y-text.tests.mjs'
import './y-map.tests.mjs'
import './y-xml.tests.mjs'
import './encode-decode.tests.mjs'
import './diff.tests.mjs'
